### ISSUE TITLE
Question, how do I create .jar?

### ISSUE THREAD

**Issue by Code-Speak** [pepsifan92/pca9685control#1]
Hello,

And first of all thanks for this binding it seems exactly what I need. I will follow the developments.

I'm just getting started with OpenHAB so forgive me if this is a rather stupid question.. But it seems if I place the pca9685control-master.zip in the addons folder of OpenHAB it doesn't start. 

How do I properly get it in the addons folder? 

As a .jar I guess since all the other addons are also .jar files. I've searched the internet for methods of creating a .jar file. But I've had no success.

Thanks in advance!

Best regards

**Comment by pepsifan92** [comment]
Hi,
I've added the compiled .jar file in the _jar_ folder. Try to add this .jar into your OpenHAB addon folder.

This binding is quite costum for my setup of hardware - not testet on any other projects. But perhaps it will work for you, too.

**Comment by Code-Speak** [comment]
Thanks! I will give it a try as soon as possible!

**Comment by Code-Speak** [comment]
Just had the chance to test it, so far it works great! No problems at all. I plan on using it to dim LED-strips using TRIACS. But the project is just getting started. If testing of the addon is needed I'll be happy to help :)

Thanks again
